2020-11-30 06:31:58,504 INFO    MainThread:3900320 [internal.py:wandb_internal():62] W&B internal server running at pid: 3900320
2020-11-30 06:31:58,506 DEBUG   HandlerThread:3900320 [handler.py:handle_request():54] handle_request: check_version
2020-11-30 06:31:58,506 INFO    WriterThread:3900320 [datastore.py:open_for_write():76] open: wandb/run-20201130_063157-gjg90dz6/run-gjg90dz6.wandb
2020-11-30 06:31:58,507 DEBUG   SenderThread:3900320 [sender.py:send():88] send: header
2020-11-30 06:31:58,507 DEBUG   SenderThread:3900320 [sender.py:send():88] send: request
2020-11-30 06:31:58,507 DEBUG   SenderThread:3900320 [sender.py:send_request():97] send_request: check_version
2020-11-30 06:31:58,509 DEBUG   Thread-4  :3900320 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): pypi.org:443
2020-11-30 06:31:58,549 DEBUG   Thread-4  :3900320 [connectionpool.py:_make_request():437] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 51947
2020-11-30 06:31:58,565 DEBUG   SenderThread:3900320 [sender.py:send():88] send: run
2020-11-30 06:31:58,568 DEBUG   SenderThread:3900320 [git.py:repo():30] git repository is invalid
2020-11-30 06:31:58,572 DEBUG   SenderThread:3900320 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-30 06:31:58,672 DEBUG   SenderThread:3900320 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-30 06:31:58,676 DEBUG   HandlerThread:3900320 [handler.py:handle_request():54] handle_request: run_start
2020-11-30 06:31:58,677 INFO    SenderThread:3900320 [dir_watcher.py:__init__():167] watching files in: wandb/run-20201130_063157-gjg90dz6/files
2020-11-30 06:31:58,677 INFO    SenderThread:3900320 [sender.py:_start_run_threads():464] run started: gjg90dz6 with start time 1606717917
2020-11-30 06:31:58,677 DEBUG   SenderThread:3900320 [sender.py:send():88] send: summary
2020-11-30 06:31:58,678 INFO    SenderThread:3900320 [sender.py:_save_file():542] saving file wandb-summary.json with policy end
2020-11-30 06:31:58,787 DEBUG   HandlerThread:3900320 [git.py:repo():30] git repository is invalid
2020-11-30 06:31:58,787 WARNING HandlerThread:3900320 [meta.py:_save_code():64] unable to save code -- program entry not found
2020-11-30 06:31:58,886 DEBUG   SenderThread:3900320 [sender.py:send():88] send: files
2020-11-30 06:31:58,886 INFO    SenderThread:3900320 [sender.py:_save_file():542] saving file wandb-metadata.json with policy now
2020-11-30 06:31:58,890 DEBUG   HandlerThread:3900320 [handler.py:handle_request():54] handle_request: status
2020-11-30 06:31:58,890 DEBUG   Thread-11 :3900320 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-30 06:31:58,891 DEBUG   SenderThread:3900320 [sender.py:send():88] send: request
2020-11-30 06:31:58,891 DEBUG   SenderThread:3900320 [sender.py:send_request():97] send_request: status
2020-11-30 06:31:58,893 DEBUG   SenderThread:3900320 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-30 06:31:59,019 DEBUG   SenderThread:3900320 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-30 06:31:59,020 DEBUG   Thread-11 :3900320 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-30 06:31:59,025 DEBUG   Thread-11 :3900320 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): storage.googleapis.com:443
2020-11-30 06:31:59,216 DEBUG   SenderThread:3900320 [sender.py:send():88] send: files
2020-11-30 06:31:59,216 INFO    SenderThread:3900320 [sender.py:_save_file():542] saving file media/graph/g.r.a.p.h._.0_summary_d0b02ed1.graph.json with policy now
2020-11-30 06:31:59,216 DEBUG   SenderThread:3900320 [sender.py:send():88] send: summary
2020-11-30 06:31:59,217 INFO    SenderThread:3900320 [sender.py:_save_file():542] saving file wandb-summary.json with policy end
2020-11-30 06:31:59,222 DEBUG   Thread-12 :3900320 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-30 06:31:59,300 DEBUG   Thread-12 :3900320 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-30 06:31:59,303 DEBUG   Thread-12 :3900320 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): storage.googleapis.com:443
2020-11-30 06:31:59,307 DEBUG   Thread-11 :3900320 [connectionpool.py:_make_request():437] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/whitera2bit/dl_hse_gan/gjg90dz6/wandb-metadata.json?Expires=1606804318&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=HGPYofhPGYzu3XRgatp0s7s8SHl8B7kuqZ%2BRw53%2BYEOJ91oAFQGjEDxuUZOAdkpb2dGAjiS3f%2B9pHYgsKZYXIwNOKv7RmLa73WJeqL8LjNpt3qayEfr8lSCpwWjA3%2FrTuGse64vRCggJTUeDMYnldTmY0m8UwqtlGbp99ps5EadJC6zA%2BkEm35WZ2zAwXraxNVF4Fics4hU%2FjuTNUCqw7dGc0V8h6VY0bhSC5g2IvZAEvW3eHJfD%2FqJEitLQshyH5XsMEbbpb7shDxT6%2FfE284CCqZgWIsOsTJKNaU2h6zRntYAcgBQEldbqfW%2B6kbC6J0MT7Hj7iN96Y2PuYW5lnQ%3D%3D HTTP/1.1" 200 0
2020-11-30 06:31:59,309 INFO    Thread-11 :3900320 [upload_job.py:push():112] Uploaded file /tmp/tmpdq67wmjzwandb/3v63amsh-wandb-metadata.json
2020-11-30 06:31:59,560 DEBUG   Thread-12 :3900320 [connectionpool.py:_make_request():437] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/whitera2bit/dl_hse_gan/gjg90dz6/media/graph/g.r.a.p.h._.0_summary_d0b02ed1.graph.json?Expires=1606804319&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=a%2B5taw%2BaQ9w9K9%2Fn6HGPEsxTmxagS%2BXQTC9JmJtIQbCtYz5jT%2FOPYcJslZck10f2T5Giealx36upoej7irf9ewAfECDWpAcNWoaNhQ%2BDz5qibJHiAwYY7ULHENZ8isw7t3TEbtt%2B2neuprRXMowUqqpoHqjinriJqla0OUPOSolSsZNz1BP9vploxZxYGkvPZXh%2BmH2L0exnEBiT4rsu6FoBl2hFOTixEfh63lshcVQH20sS6tj4n2G3jKbCNW7Z2VsoyujRLFxPJ017SaS7S30pQLrgPuFNBwQqgqaB1%2FqyncdQJSmXhGwQIh51Drc2BZcL7WDb1D%2BCv76vduRRzA%3D%3D HTTP/1.1" 200 0
2020-11-30 06:31:59,561 INFO    Thread-12 :3900320 [upload_job.py:push():112] Uploaded file /tmp/tmpdq67wmjzwandb/28qtmhci-media/graph/g.r.a.p.h._.0_summary_d0b02ed1.graph.json
2020-11-30 06:31:59,678 INFO    Thread-8  :3900320 [dir_watcher.py:_on_file_created():215] file/dir created: wandb/run-20201130_063157-gjg90dz6/files/wandb-summary.json
2020-11-30 06:31:59,679 INFO    Thread-8  :3900320 [dir_watcher.py:_on_file_created():215] file/dir created: wandb/run-20201130_063157-gjg90dz6/files/output.log
2020-11-30 06:31:59,679 INFO    Thread-8  :3900320 [dir_watcher.py:_on_file_created():215] file/dir created: wandb/run-20201130_063157-gjg90dz6/files/media/graph/g.r.a.p.h._.0_summary_d0b02ed1.graph.json
2020-11-30 06:31:59,679 INFO    Thread-8  :3900320 [dir_watcher.py:_on_file_created():215] file/dir created: wandb/run-20201130_063157-gjg90dz6/files/requirements.txt
2020-11-30 06:31:59,679 INFO    Thread-8  :3900320 [dir_watcher.py:_on_file_created():215] file/dir created: wandb/run-20201130_063157-gjg90dz6/files/wandb-metadata.json
2020-11-30 06:31:59,679 INFO    Thread-8  :3900320 [dir_watcher.py:_on_file_created():215] file/dir created: wandb/run-20201130_063157-gjg90dz6/files/media
2020-11-30 06:31:59,679 INFO    Thread-8  :3900320 [dir_watcher.py:_on_file_created():215] file/dir created: wandb/run-20201130_063157-gjg90dz6/files/media/graph
2020-11-30 06:32:01,218 DEBUG   Thread-5  :3900320 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-30 06:32:01,380 DEBUG   Thread-5  :3900320 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/whitera2bit/dl_hse_gan/gjg90dz6/file_stream HTTP/1.1" 200 None
2020-11-30 06:32:03,615 DEBUG   Thread-5  :3900320 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/whitera2bit/dl_hse_gan/gjg90dz6/file_stream HTTP/1.1" 200 None
2020-11-30 06:32:03,679 INFO    Thread-8  :3900320 [dir_watcher.py:_on_file_modified():228] file/dir modified: wandb/run-20201130_063157-gjg90dz6/files/output.log
2020-11-30 06:32:03,724 DEBUG   SenderThread:3900320 [sender.py:send():88] send: files
2020-11-30 06:32:03,724 INFO    SenderThread:3900320 [sender.py:_save_file():542] saving file media/images/Sample_0_65692db1.png with policy now
2020-11-30 06:32:03,728 DEBUG   Thread-13 :3900320 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-30 06:32:03,729 DEBUG   SenderThread:3900320 [sender.py:send():88] send: history
2020-11-30 06:32:03,729 DEBUG   SenderThread:3900320 [sender.py:send():88] send: summary
2020-11-30 06:32:03,730 INFO    SenderThread:3900320 [sender.py:_save_file():542] saving file wandb-summary.json with policy end
2020-11-30 06:32:03,809 DEBUG   Thread-13 :3900320 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-30 06:32:03,813 DEBUG   Thread-13 :3900320 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): storage.googleapis.com:443
2020-11-30 06:32:03,964 DEBUG   HandlerThread:3900320 [handler.py:handle_request():54] handle_request: pause
2020-11-30 06:32:03,964 INFO    HandlerThread:3900320 [handler.py:handle_request_pause():222] stopping system metrics thread
2020-11-30 06:32:04,148 DEBUG   Thread-13 :3900320 [connectionpool.py:_make_request():437] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/whitera2bit/dl_hse_gan/gjg90dz6/media/images/Sample_0_65692db1.png?Expires=1606804323&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=DJPfQ7V%2Fg1CVe1oO61YqQwEEespUf6FM6ZNHOQAcoWfVLttNPVVLKhJcKdgqXAMjCLuPLtO1H0YKbEyvVks0TdTT3fgsnEayzK9tOEbVUZ2LQ8PTFvUZech7%2BPetIr0i%2FlGiokFGK1V6aAJp6WXAZWuGOeTwWi8ERyf0LEe6p%2FbegsP1X0VBtygkC4RBhqE5xx7r7JHXTbT86CIdcjplulIHNHkwBb5M%2FhmCV%2FMRH0KX6FZ8%2BocLR40sRZxzw8VsgMMRjUsYJHATIDkllrzQn6aA2Sg6nIip2kJbYsGpslkGPjHGxdE0on2RDBLhpMNMUq2If52nN2zF8w7KQIc0pw%3D%3D HTTP/1.1" 200 0
2020-11-30 06:32:04,150 INFO    Thread-13 :3900320 [upload_job.py:push():112] Uploaded file /tmp/tmpdq67wmjzwandb/1owqizks-media/images/Sample_0_65692db1.png
2020-11-30 06:32:04,569 DEBUG   SenderThread:3900320 [sender.py:send():88] send: stats
2020-11-30 06:32:04,680 INFO    Thread-8  :3900320 [dir_watcher.py:_on_file_modified():228] file/dir modified: wandb/run-20201130_063157-gjg90dz6/files/output.log
2020-11-30 06:32:04,680 INFO    Thread-8  :3900320 [dir_watcher.py:_on_file_modified():228] file/dir modified: wandb/run-20201130_063157-gjg90dz6/files/wandb-summary.json
2020-11-30 06:32:04,680 INFO    Thread-8  :3900320 [dir_watcher.py:_on_file_created():215] file/dir created: wandb/run-20201130_063157-gjg90dz6/files/media/images/Sample_0_65692db1.png
2020-11-30 06:32:04,680 INFO    Thread-8  :3900320 [dir_watcher.py:_on_file_modified():228] file/dir modified: wandb/run-20201130_063157-gjg90dz6/files/media
2020-11-30 06:32:04,680 INFO    Thread-8  :3900320 [dir_watcher.py:_on_file_created():215] file/dir created: wandb/run-20201130_063157-gjg90dz6/files/media/images
2020-11-30 06:32:06,657 DEBUG   Thread-5  :3900320 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/whitera2bit/dl_hse_gan/gjg90dz6/file_stream HTTP/1.1" 200 None
2020-11-30 06:32:14,023 DEBUG   HandlerThread:3900320 [handler.py:handle_request():54] handle_request: status
2020-11-30 06:32:14,023 DEBUG   SenderThread:3900320 [sender.py:send():88] send: request
2020-11-30 06:32:14,024 DEBUG   SenderThread:3900320 [sender.py:send_request():97] send_request: status
2020-11-30 06:32:14,026 DEBUG   SenderThread:3900320 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-30 06:32:14,101 DEBUG   SenderThread:3900320 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-30 06:32:29,103 DEBUG   HandlerThread:3900320 [handler.py:handle_request():54] handle_request: status
2020-11-30 06:32:29,104 DEBUG   SenderThread:3900320 [sender.py:send():88] send: request
2020-11-30 06:32:29,104 DEBUG   SenderThread:3900320 [sender.py:send_request():97] send_request: status
2020-11-30 06:32:29,106 DEBUG   SenderThread:3900320 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-30 06:32:29,179 DEBUG   SenderThread:3900320 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-30 06:32:36,721 DEBUG   Thread-5  :3900320 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/whitera2bit/dl_hse_gan/gjg90dz6/file_stream HTTP/1.1" 200 None
2020-11-30 06:32:44,182 DEBUG   HandlerThread:3900320 [handler.py:handle_request():54] handle_request: status
2020-11-30 06:32:44,182 DEBUG   SenderThread:3900320 [sender.py:send():88] send: request
2020-11-30 06:32:44,182 DEBUG   SenderThread:3900320 [sender.py:send_request():97] send_request: status
2020-11-30 06:32:44,185 DEBUG   SenderThread:3900320 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-30 06:32:44,250 DEBUG   SenderThread:3900320 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-30 06:32:59,252 DEBUG   HandlerThread:3900320 [handler.py:handle_request():54] handle_request: status
2020-11-30 06:32:59,252 DEBUG   SenderThread:3900320 [sender.py:send():88] send: request
2020-11-30 06:32:59,253 DEBUG   SenderThread:3900320 [sender.py:send_request():97] send_request: status
2020-11-30 06:32:59,255 DEBUG   SenderThread:3900320 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-30 06:32:59,319 DEBUG   SenderThread:3900320 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-30 06:33:06,045 DEBUG   HandlerThread:3900320 [handler.py:handle_request():54] handle_request: resume
2020-11-30 06:33:06,046 INFO    HandlerThread:3900320 [handler.py:handle_request_resume():217] starting system metrics thread
2020-11-30 06:33:06,046 DEBUG   HandlerThread:3900320 [handler.py:handle_request():54] handle_request: pause
2020-11-30 06:33:06,046 INFO    HandlerThread:3900320 [handler.py:handle_request_pause():222] stopping system metrics thread
2020-11-30 06:33:06,579 DEBUG   SenderThread:3900320 [sender.py:send():88] send: stats
2020-11-30 06:33:06,623 DEBUG   Thread-5  :3900320 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/whitera2bit/dl_hse_gan/gjg90dz6/file_stream HTTP/1.1" 404 None
2020-11-30 06:33:06,675 DEBUG   HandlerThread:3900320 [handler.py:handle_request():54] handle_request: resume
2020-11-30 06:33:06,676 INFO    HandlerThread:3900320 [handler.py:handle_request_resume():217] starting system metrics thread
2020-11-30 06:33:06,677 DEBUG   HandlerThread:3900320 [handler.py:handle_request():54] handle_request: pause
2020-11-30 06:33:06,677 INFO    HandlerThread:3900320 [handler.py:handle_request_pause():222] stopping system metrics thread
2020-11-30 06:33:06,921 DEBUG   HandlerThread:3900320 [handler.py:handle_request():54] handle_request: resume
2020-11-30 06:33:06,921 INFO    HandlerThread:3900320 [handler.py:handle_request_resume():217] starting system metrics thread
2020-11-30 06:33:06,922 DEBUG   SenderThread:3900320 [sender.py:send():88] send: config
2020-11-30 06:33:06,927 DEBUG   SenderThread:3900320 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-30 06:33:06,932 DEBUG   HandlerThread:3900320 [handler.py:handle_request():54] handle_request: poll_exit
2020-11-30 06:33:07,018 DEBUG   SenderThread:3900320 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 400 None
2020-11-30 06:33:07,020 ERROR   SenderThread:3900320 [internal_api.py:execute():131] 400 response executing GraphQL.
2020-11-30 06:33:07,020 ERROR   SenderThread:3900320 [internal_api.py:execute():132] {"errors":[{"message":"run whitera2bit/dl_hse_gan/gjg90dz6 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2020-11-30 06:33:07,708 INFO    Thread-8  :3900320 [dir_watcher.py:_on_file_modified():228] file/dir modified: wandb/run-20201130_063157-gjg90dz6/files/output.log
2020-11-30 06:33:07,708 INFO    Thread-8  :3900320 [dir_watcher.py:_on_file_created():215] file/dir created: wandb/run-20201130_063157-gjg90dz6/files/code/_session_history.ipynb
2020-11-30 06:33:07,708 INFO    Thread-8  :3900320 [dir_watcher.py:_on_file_created():215] file/dir created: wandb/run-20201130_063157-gjg90dz6/files/code
2020-11-30 06:33:07,932 INFO    WriterThread:3900320 [datastore.py:close():257] close: wandb/run-20201130_063157-gjg90dz6/run-gjg90dz6.wandb
2020-11-30 06:33:07,933 INFO    HandlerThread:3900320 [handler.py:finish():267] shutting down handler
2020-11-30 06:33:07,933 ERROR   MainThread:3900320 [internal.py:wandb_internal():128] Thread SenderThread:
Traceback (most recent call last):
  File "/home/pafakanov/data/anaconda3/lib/python3.7/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/pafakanov/data/anaconda3/lib/python3.7/site-packages/wandb/internal/internal_api.py", line 968, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/pafakanov/data/anaconda3/lib/python3.7/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/pafakanov/data/anaconda3/lib/python3.7/site-packages/wandb/internal/internal_api.py", line 134, in execute
    six.reraise(*sys.exc_info())
  File "/home/pafakanov/data/anaconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/pafakanov/data/anaconda3/lib/python3.7/site-packages/wandb/internal/internal_api.py", line 128, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/pafakanov/data/anaconda3/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/pafakanov/data/anaconda3/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/pafakanov/data/anaconda3/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/pafakanov/data/anaconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pafakanov/data/anaconda3/lib/python3.7/site-packages/wandb/internal/internal_util.py", line 33, in run
    self._run()
  File "/home/pafakanov/data/anaconda3/lib/python3.7/site-packages/wandb/internal/internal_util.py", line 60, in _run
    self._process(record)
  File "/home/pafakanov/data/anaconda3/lib/python3.7/site-packages/wandb/internal/internal.py", line 232, in _process
    self._sm.send(record)
  File "/home/pafakanov/data/anaconda3/lib/python3.7/site-packages/wandb/internal/sender.py", line 90, in send
    send_handler(record)
  File "/home/pafakanov/data/anaconda3/lib/python3.7/site-packages/wandb/internal/sender.py", line 535, in send_config
    name=self._run.run_id, config=config_dict, **self._api_settings
  File "/home/pafakanov/data/anaconda3/lib/python3.7/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    raise CommError(err.response, err)
wandb.errors.error.CommError: <Response [400]>
2020-11-30 06:33:08,007 INFO    MainThread:3900320 [internal.py:handle_exit():137] Internal process exited
2020-11-30 06:33:08,008 DEBUG   raven-sentry.BackgroundWorker:3900320 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
